/**
 * Central Feature Registry for Enamels Production System Control.
 * Synchronized with exact navbar and feature names across the system.
 */

const MODULES = [
  { id: 'DASHBOARD', name: 'Dashboard & Reports' },
  { id: 'ORDERS', name: 'Orders Management' },
  { id: 'STORE', name: 'Store & Warehouse' },
  { id: 'PRODUCTION', name: 'Production & Manufacturing' },
  { id: 'DELIVERY', name: 'Dispatch & Delivery' },
  { id: 'MARKETING', name: 'Marketing & Field Activities' },
  { id: 'FINANCE', name: 'Finance & Cash Management' },
  { id: 'OUTLET', name: 'Outlet & POS' },
  { id: 'ASM', name: 'ASM & Bulk Vendors' },
];

const FEATURES = [
  // ── DASHBOARD ──
  {
    id: 'DASHBOARD_VIEW',
    name: 'Dashboard',
    description: 'Access main production dashboard, status cards, and throughput summaries.',
    module: 'DASHBOARD',
    defaultProfiles: ['SUPER_ADMIN', 'ADMIN', 'CEO', 'ORDER_ENTRY'],
  },
  {
    id: 'ANALYTICS_VIEW',
    name: 'Analytics',
    description: 'Access advanced analytics, charts, and performance metrics.',
    module: 'DASHBOARD',
    defaultProfiles: ['SUPER_ADMIN', 'ADMIN', 'CEO'],
  },
  {
    id: 'PRODUCT_DATA_VIEW',
    name: 'Product Data',
    description: 'Inspect article sales, catalog throughput, and product metrics.',
    module: 'DASHBOARD',
    defaultProfiles: ['SUPER_ADMIN', 'ADMIN', 'CEO'],
  },
  {
    id: 'CEO_DASHBOARD_VIEW',
    name: 'Executive Dashboard',
    description: 'High-level business intelligence and strategic executive dashboards.',
    module: 'DASHBOARD',
    defaultProfiles: ['CEO', 'SUPER_ADMIN'],
  },

  // ── ORDERS ──
  {
    id: 'ORDER_VIEW',
    name: 'Orders',
    description: 'View production orders list, customer information, and stage progressions.',
    module: 'ORDERS',
    defaultProfiles: ['SUPER_ADMIN', 'ADMIN', 'CEO', 'FAISAL', 'ORDER_ENTRY', 'INVENTORY_VIEW', 'OUTLET', 'STORE'],
  },
  {
    id: 'ORDER_ENTRY',
    name: 'Order Entry',
    description: 'Submit and enter new orders into the production pipeline.',
    module: 'ORDERS',
    defaultProfiles: ['ORDER_ENTRY', 'FAISAL', 'SUPER_ADMIN', 'ADMIN'],
  },
  {
    id: 'ORDER_EDIT',
    name: 'Edit Request',
    description: 'Adjust order amounts, line items, and product configurations.',
    module: 'ORDERS',
    defaultProfiles: ['SUPER_ADMIN', 'ADMIN'],
  },
  {
    id: 'ORDER_CANCEL',
    name: 'Order Cancellation',
    description: 'Request, process, and approve order cancellations.',
    module: 'ORDERS',
    defaultProfiles: ['SUPER_ADMIN', 'ADMIN', 'FAISAL', 'ORDER_ENTRY', 'OUTLET', 'INVENTORY_VIEW'],
  },
  {
    id: 'ORDER_TRACK',
    name: 'Order Track',
    description: 'Lookup order progression by Order Number, Invoice #, or customer phone.',
    module: 'ORDERS',
    defaultProfiles: ['SUPER_ADMIN', 'ADMIN', 'CEO', 'OUTLET', 'INVENTORY_VIEW', 'FAISAL', 'STORE'],
  },
  {
    id: 'RETURN_EXCHANGE',
    name: 'Return & Exchange',
    description: 'Process customer returns, replacement orders, and inspect incoming returned items.',
    module: 'ORDERS',
    defaultProfiles: ['INVENTORY_VIEW', 'STORE', 'STORE_EMPLOYEE', 'SUPER_ADMIN', 'ADMIN'],
  },
  {
    id: 'ORDER_VERIFICATION',
    name: 'Verification',
    description: 'Audit and verify incoming orders, custom measurements, and specifications before production release.',
    module: 'ORDERS',
    defaultProfiles: ['INVENTORY_VIEW', 'SUPER_ADMIN', 'ADMIN'],
  },
  {
    id: 'RETURNED_FROM_VERIFICATION',
    name: 'Return from Verification',
    description: 'Review orders returned for correction from Verification to Faisal / Order Entry.',
    module: 'ORDERS',
    defaultProfiles: ['FAISAL', 'SUPER_ADMIN', 'ADMIN'],
  },
  {
    id: 'ORDER_DELETE',
    name: 'Deleted Orders',
    description: 'Permanently delete and manage deleted orders in the system.',
    module: 'ORDERS',
    defaultProfiles: ['SUPER_ADMIN', 'ADMIN'],
  },
  {
    id: 'ORDER_EXCEL_EXPORT',
    name: 'Export Orders',
    description: 'Export filtered production orders into spreadsheets.',
    module: 'ORDERS',
    defaultProfiles: ['SUPER_ADMIN', 'ADMIN', 'CEO', 'FAISAL'],
  },

  // ── STORE ──
  {
    id: 'STORE_DASHBOARD',
    name: 'Dashboard',
    description: 'Access warehouse inventory stats, queues, and order readiness.',
    module: 'STORE',
    defaultProfiles: ['STORE', 'STORE_EMPLOYEE', 'SUPER_ADMIN', 'ADMIN'],
  },
  {
    id: 'STORE_TASKS',
    name: 'My Tasks',
    description: 'Process incoming order items and allocate inventory.',
    module: 'STORE',
    defaultProfiles: ['STORE', 'STORE_EMPLOYEE', 'OUTLET', 'PRODUCTION', 'PRODUCTION_IN', 'PRODUCTION_OUT', 'LOGO_DESIGN', 'LOGO_DESIGN_EMPLOYEE', 'LOGO_DESIGNER', 'OUT_FOR_DELIVERY'],
  },
  {
    id: 'STORE_ASM_ALLOCATION',
    name: 'ASM Allocate',
    description: 'Allocate warehouse stock directly to ASM bulk orders.',
    module: 'STORE',
    defaultProfiles: ['STORE', 'SUPER_ADMIN', 'ADMIN'],
  },
  {
    id: 'STORE_SEND_TO_PRODUCTION',
    name: 'Send to Production',
    description: 'Route unfulfilled store items to factory production line.',
    module: 'STORE',
    defaultProfiles: ['STORE'],
  },
  {
    id: 'STORE_RECEIVE',
    name: 'Receive',
    description: 'Receive completed goods returning from production.',
    module: 'STORE',
    defaultProfiles: ['STORE', 'SUPER_ADMIN', 'ADMIN'],
  },
  {
    id: 'STORE_REPLACEMENTS',
    name: 'Replacements',
    description: 'Manage replacement garments and exchange items.',
    module: 'STORE',
    defaultProfiles: ['STORE', 'FAISAL'],
  },
  {
    id: 'STORE_RETURNS',
    name: 'Returns',
    description: 'Process damaged or returned items back into store inventory.',
    module: 'STORE',
    defaultProfiles: ['STORE', 'SUPER_ADMIN', 'ADMIN', 'INVENTORY_VIEW'],
  },
  {
    id: 'STORE_INVENTORY_AUDIT',
    name: 'Inventory Audit',
    description: 'Perform physical stock counts, reconciliations, and audit reviews.',
    module: 'STORE',
    defaultProfiles: ['STORE', 'STORE_EMPLOYEE', 'SUPER_ADMIN', 'ADMIN', 'INVENTORY_VIEW', 'FAISAL'],
  },
  {
    id: 'DEMAND_LEDGER_VIEW',
    name: 'Demand Ledger',
    description: 'Inspect factory-to-outlet delivery demand history and branch replenishment logs.',
    module: 'STORE',
    defaultProfiles: ['FAISAL', 'STORE', 'SUPER_ADMIN', 'ADMIN'],
  },
  {
    id: 'WAREHOUSE_VIEW',
    name: 'Warehouse',
    description: 'View raw warehouse quantities, color/size stock, and adjustments.',
    module: 'STORE',
    defaultProfiles: ['STORE', 'SUPER_ADMIN', 'ADMIN', 'FAISAL', 'INVENTORY_VIEW', 'OUTLET'],
  },

  // ── PRODUCTION ──
  {
    id: 'PRODUCTION_DASHBOARD',
    name: 'Production',
    description: 'Manufacturing pipeline overview, departmental queues, and worker status.',
    module: 'PRODUCTION',
    defaultProfiles: ['PRODUCTION', 'SUPER_ADMIN', 'ADMIN'],
  },
  {
    id: 'PRODUCTION_ACCEPTANCE',
    name: 'Production Acceptance',
    description: 'Review design specs and accept orders into production departments.',
    module: 'PRODUCTION',
    defaultProfiles: ['PRODUCTION'],
  },
  {
    id: 'PRODUCTION_IN',
    name: 'Alteration In',
    description: 'Log and process alteration jobs entering production floor.',
    module: 'PRODUCTION',
    defaultProfiles: ['PRODUCTION', 'PRODUCTION_IN'],
  },
  {
    id: 'PRODUCTION_OUT',
    name: 'Alteration Out',
    description: 'Mark production jobs complete and handover to store / dispatch.',
    module: 'PRODUCTION',
    defaultProfiles: ['PRODUCTION', 'PRODUCTION_OUT'],
  },
  {
    id: 'ALTERATION_PRODUCTION',
    name: 'Alteration',
    description: 'Manage alterations, repairs, and custom resizing.',
    module: 'PRODUCTION',
    defaultProfiles: ['PRODUCTION', 'PRODUCTION_IN', 'PRODUCTION_OUT', 'OUTLET'],
  },
  {
    id: 'ENGRAVING_QUEUE',
    name: 'Engraving',
    description: 'Process custom name engravings, logo setups, and embroidery files.',
    module: 'PRODUCTION',
    defaultProfiles: ['LOGO_DESIGN', 'LOGO_DESIGN_EMPLOYEE', 'LOGO_DESIGNER', 'OUTLET'],
  },

  // ── DELIVERY ──
  {
    id: 'DISPATCH_DASHBOARD',
    name: 'Dispatch',
    description: 'Overview of ready orders, packing progress, and delivery routes.',
    module: 'DELIVERY',
    defaultProfiles: ['DISPATCH', 'SUPER_ADMIN', 'ADMIN'],
  },
  {
    id: 'DISPATCH_TASKS',
    name: 'My Tasks',
    description: 'Pack orders, print labels, and assign packages to couriers or drivers.',
    module: 'DELIVERY',
    defaultProfiles: ['DISPATCH', 'SUPER_ADMIN', 'ADMIN', 'FAISAL'],
  },
  {
    id: 'END_DISPATCH',
    name: 'End Dispatch',
    description: 'Complete dispatch manifests and execute courier handovers.',
    module: 'DELIVERY',
    defaultProfiles: ['DISPATCH', 'SUPER_ADMIN', 'ADMIN'],
  },
  {
    id: 'DELIVERY_DASHBOARD',
    name: 'Deliveries',
    description: 'Access assigned delivery tasks, customer contacts, and drop-off queues.',
    module: 'DELIVERY',
    defaultProfiles: ['DELIVERY_BOY'],
  },
  {
    id: 'DELIVERY_MARK_DELIVERED',
    name: 'Mark Delivered',
    description: 'Confirm delivery to customer, record cash collected, and upload proof.',
    module: 'DELIVERY',
    defaultProfiles: ['DELIVERY_BOY', 'DISPATCH', 'SUPER_ADMIN', 'ADMIN'],
  },
  {
    id: 'REFUND_MANAGEMENT',
    name: 'Refund Management',
    description: 'Record failed deliveries, customer rejections, and refund returns.',
    module: 'DELIVERY',
    defaultProfiles: ['DELIVERY_BOY', 'DISPATCH'],
  },
  {
    id: 'POSTEX_DASHBOARD',
    name: 'PostEx Integration',
    description: 'Automated PostEx consignment tracking and status reconciliation.',
    module: 'DELIVERY',
    defaultProfiles: ['SUPER_ADMIN', 'ADMIN', 'DISPATCH'],
  },

  // ── MARKETING ──
  {
    id: 'MARKETING_DASHBOARD',
    name: 'Marketing',
    description: 'Personal field visit dashboard, today visits count, and quick summary.',
    module: 'MARKETING',
    defaultProfiles: ['MARKETING', 'SUPER_ADMIN', 'ADMIN'],
  },
  {
    id: 'MARKETING_LOCATION_ENTRY',
    name: 'Record Visit',
    description: 'Record field activities, visited hospitals/companies, notes, and coordinates.',
    module: 'MARKETING',
    defaultProfiles: ['MARKETING'],
  },
  {
    id: 'MARKETING_ACTIVITY_HISTORY',
    name: 'Visit History',
    description: 'View full history of logged marketing visits and client interactions.',
    module: 'MARKETING',
    defaultProfiles: ['MARKETING', 'SUPER_ADMIN', 'ADMIN'],
  },
  {
    id: 'MARKETING_MAP_VIEW',
    name: 'Map View',
    description: 'Inspect visual map representation of marketing visits and areas.',
    module: 'MARKETING',
    defaultProfiles: ['MARKETING', 'SUPER_ADMIN', 'ADMIN'],
  },
  {
    id: 'ADMIN_MARKETING_VIEW',
    name: 'Marketing',
    description: 'Supervise all marketing employees, monitor real-time visits, and filter by hospital/company.',
    module: 'MARKETING',
    defaultProfiles: ['SUPER_ADMIN', 'ADMIN', 'CEO'],
  },

  // ── FINANCE ──
  {
    id: 'BANK_DEPOSIT',
    name: 'Bank Deposit',
    description: 'Calculate daily requirements, submit cash deposits, and track pending ledgers.',
    module: 'FINANCE',
    defaultProfiles: ['OUTLET', 'SUPER_ADMIN', 'ADMIN', 'SOFTWARE_SETTINGS'],
  },
  {
    id: 'GENERAL_ENTRIES',
    name: 'General Entries',
    description: 'Record daily cash expense deductions, refreshment receipts, and petty cash.',
    module: 'FINANCE',
    defaultProfiles: ['OUTLET', 'SUPER_ADMIN', 'ADMIN'],
  },
  {
    id: 'PAYMENT_METHOD_CHANGE',
    name: 'Change Payment Method',
    description: 'Correct payment channels (Cash vs Online vs Card) for settled transactions.',
    module: 'FINANCE',
    defaultProfiles: ['SOFTWARE_SETTINGS', 'SUPER_ADMIN', 'ADMIN'],
  },
  {
    id: 'FINANCIAL_REPORTS',
    name: 'Financial Reports',
    description: 'Access 4-tier financial breakdowns, gross vs net revenue, and cash ledgers.',
    module: 'FINANCE',
    defaultProfiles: ['SUPER_ADMIN', 'ADMIN', 'CEO', 'OUTLET'],
  },

  // ── OUTLET ──
  {
    id: 'OUTLET_DASHBOARD',
    name: 'Outlet Dashboard',
    description: 'Branch overview, today POS sales, balance collections, and deposit alerts.',
    module: 'OUTLET',
    defaultProfiles: ['OUTLET', 'SUPER_ADMIN', 'ADMIN'],
  },
  {
    id: 'OUTLET_POS',
    name: 'POS',
    description: 'Access barcode scanner, register sessions, and retail checkout.',
    module: 'OUTLET',
    defaultProfiles: ['OUTLET'],
  },
  {
    id: 'OUTLET_ORDER_VIEW',
    name: 'Orders',
    description: 'Search, look up, and inspect historical outlet orders and balance receipts.',
    module: 'OUTLET',
    defaultProfiles: ['OUTLET', 'SUPER_ADMIN', 'ADMIN'],
  },
  {
    id: 'OUTLET_INVOICE_QUOTATION',
    name: 'Invoice / Quotation',
    description: 'Generate and print branded Meezan Bank A4 invoices and quotations.',
    module: 'OUTLET',
    defaultProfiles: ['OUTLET'],
  },
  {
    id: 'OUTLET_ORDER_ENTRY',
    name: 'Outlet Order Entry',
    description: 'Take custom made-to-measure orders directly from retail customers.',
    module: 'OUTLET',
    defaultProfiles: ['OUTLET'],
  },
  {
    id: 'OUTLET_STOCK_REQUEST',
    name: 'Outlet Requests',
    description: 'Demand articles and inventory replenishments from main warehouse.',
    module: 'OUTLET',
    defaultProfiles: ['OUTLET'],
  },
  {
    id: 'OUTLET_TRANSFERS',
    name: 'Transfers',
    description: 'Transfer stock between retail branches and record gate handovers.',
    module: 'OUTLET',
    defaultProfiles: ['OUTLET', 'STORE'],
  },
  {
    id: 'OUTLET_GATE_PASS',
    name: 'Gate Pass',
    description: 'Print customer balance verification gate passes.',
    module: 'OUTLET',
    defaultProfiles: ['OUTLET'],
  },
  {
    id: 'OUTLET_IN_DISPATCH',
    name: 'In Dispatch',
    description: 'Track factory-to-outlet incoming shipments.',
    module: 'OUTLET',
    defaultProfiles: ['OUTLET'],
  },
  {
    id: 'OUTLET_TASKS',
    name: 'My Tasks',
    description: 'Track orders, alteration jobs, engraving requests, and branch task queues.',
    module: 'OUTLET',
    defaultProfiles: ['OUTLET', 'SUPER_ADMIN', 'ADMIN'],
  },

  // ── ASM ──
  {
    id: 'ASM_DASHBOARD',
    name: 'ASM Dashboard',
    description: 'Area Sales Manager portal for institutional clients and bulk requests.',
    module: 'ASM',
    defaultProfiles: ['ASM', 'SUPER_ADMIN', 'ADMIN'],
  },
  {
    id: 'ADMIN_ASM_APPROVAL',
    name: 'ASM Approval',
    description: 'Approve, price-adjust, or reject institutional bulk orders submitted by ASM.',
    module: 'ASM',
    defaultProfiles: ['SUPER_ADMIN', 'ADMIN'],
  },
  {
    id: 'ASM_ORDER_EDIT',
    name: 'Edit Order',
    description: 'Edit quantities, line items, and resubmit revised versions for approval.',
    module: 'ASM',
    defaultProfiles: ['ASM', 'SUPER_ADMIN', 'ADMIN'],
  },
  {
    id: 'ASM_BULK_REQUEST',
    name: 'Create Bulk Order',
    description: 'Submit institutional quotation orders for schools, hospitals, and clinics.',
    module: 'ASM',
    defaultProfiles: ['ASM'],
  },
  {
    id: 'ASM_VENDORS_ADMIN',
    name: 'Vendors & Institutional Orders',
    description: 'Admin overview of all vendor requests and order fulfillment status.',
    module: 'ASM',
    defaultProfiles: ['SUPER_ADMIN', 'ADMIN'],
  },
];

const ALL_PROFILES = [
  'SUPER_ADMIN',
  'ADMIN',
  'CEO',
  'SOFTWARE_SETTINGS',
  'OUTLET',
  'STORE',
  'MARKETING',
  'ASM',
  'PRODUCTION',
  'PRODUCTION_IN',
  'PRODUCTION_OUT',
  'LOGO_DESIGN',
  'DISPATCH',
  'DELIVERY_BOY',
  'INVENTORY_VIEW',
  'ORDER_ENTRY',
  'FAISAL',
];

module.exports = {
  MODULES,
  FEATURES,
  ALL_PROFILES,
};
