import React, { useState, useCallback, useMemo, useEffect } from 'react';
import { useSearchParams } from 'react-router-dom';
import api from '../services/api';
import { useAuth } from '../context/AuthContext';
import { Search, User, Phone, MapPin, ShoppingBag, Ruler, FileText, CreditCard, Send, CheckCircle, ChevronLeft, ChevronRight, Plus, X, RefreshCw } from 'lucide-react';
import toast from 'react-hot-toast';

const STEPS = ['Customer', 'Products', 'Engraving', 'Measurements', 'Destination', 'Place Order'];

const DESTINATIONS = [
  { value: 'STORE', label: 'Send to Store', desc: 'Route directly to Store' },
  { value: 'LOGO_DESIGN', label: 'Send to Logo Department', desc: 'Logo team receives immediately' },
  { value: 'PRODUCTION', label: 'Send to Production', desc: 'Production receives immediately' }
];

const EMPTY_MEASUREMENT_FIELDS = {
  'Shirt Length': '', 'Shoulder': '', 'Sleeves Length': '', 'Sleeves Hole': '',
  'Chest': '', 'Bottom': '', 'Waist': '', 'Length': '', 'Pancha': '', 'Thighs': '', 'Asan': ''
};

const SLEEVE_LENGTH_OPTIONS = [
  { value: 'Full', label: 'Full', labelUrdu: 'پوری بازو' },
  { value: 'Half', label: 'Half', labelUrdu: 'آدھی بازو' },
  { value: 'Three-Quarter', label: 'Three-Quarter', labelUrdu: 'تین چوتھائی بازو' }
];

const SHIRT_LENGTH_OPTIONS = [
  { value: 'Short', label: 'Short', labelUrdu: 'چھوٹی شرٹ' },
  { value: 'Regular', label: 'Regular', labelUrdu: 'نارمل شرٹ' },
  { value: 'Long', label: 'Long', labelUrdu: 'لمبی شرٹ' }
];

const FIELD_NAME_MAP = {
  chest: 'Chest', waist: 'Waist', shoulder: 'Shoulder',
  length: 'Length', sleeve: 'Sleeves Length', thigh: 'Thighs',
  mori: 'Mori', bottom: 'Bottom',
  shirtLength: 'Shirt Length', bottomWidth: 'Bottom Width',
  bottomZeer: 'Bottom Zeer', neck: 'Neck', cuff: 'Cuff',
  armhole: 'Armhole', hip: 'Hip', trouserLength: 'Trouser Length',
  sleevesLength: 'Sleeves Length', sleevesHole: 'Sleeves Hole',
  pancha: 'Pancha', thighs: 'Thighs', asan: 'Asan'
};

const OutletOrderEntry = () => {
  const { user } = useAuth();
  const outletName = user?.name || 'Outlet';
  const [searchParams] = useSearchParams();
  const prefilledOrderNumber = searchParams.get('orderNumber') || '';

  const [step, setStep] = useState(0);

  // --- Customer mode ---
  const [customerMode, setCustomerMode] = useState(null); // 'existing' | 'new' | null
  const [searchQuery, setSearchQuery] = useState('');
  const [searchResults, setSearchResults] = useState([]);
  const [showResults, setShowResults] = useState(false);
  const [clientData, setClientData] = useState(null);
  const [recentOrders, setRecentOrders] = useState([]);
  const [lookupLoading, setLookupLoading] = useState(false);
  const [lookedUp, setLookedUp] = useState(false);

  const [customer, setCustomer] = useState({ name: '', phone: '', address: '', city: '', notes: '' });

  // --- Order number ---
  const [autoGeneratedOrderNumber, setAutoGeneratedOrderNumber] = useState('');
  const [autoGeneratedInvoiceNumber, setAutoGeneratedInvoiceNumber] = useState('');

  // --- Products ---
  const [products, setProducts] = useState([]);
  const [newProduct, setNewProduct] = useState({
    name: '', fabric: '', color: '', size: '', quantity: 1, unitPrice: 0,
    design: '', stitchingNotes: '', accessories: '', sleeveLength: '', shirtLength: '', measurementSpecialNote: ''
  });

  // --- Engraving ---
  const [engravingRequired, setEngravingRequired] = useState(false);
  const [engravingText, setEngravingText] = useState('');
  const [engravingType, setEngravingType] = useState('direct');
  const [engravingInstructions, setEngravingInstructions] = useState('');
  const [logoRequired, setLogoRequired] = useState(false);
  const [engravingNames, setEngravingNames] = useState([]);
  const [engravingLogos, setEngravingLogos] = useState([]);
  const [logoDesign, setLogoDesign] = useState('');

  // --- Special Notes ---
  const [specialNotes, setSpecialNotes] = useState('');

  // --- Measurements ---
  const [sizeData, setSizeData] = useState({});
  const [clientStandardSizes, setClientStandardSizes] = useState([]);
  const [clientMeasurements, setClientMeasurements] = useState({});
  const [sizingMode, setSizingMode] = useState(null);
  const [selectedStandardSize, setSelectedStandardSize] = useState('');
  const [clientMeasurementChart, setClientMeasurementChart] = useState('');

  // --- Payment ---
  const [advanceAmount, setAdvanceAmount] = useState(0);

  // --- Destination ---
  const [destination, setDestination] = useState('');

  // --- Submit ---
  const [submitting, setSubmitting] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const [createdOrder, setCreatedOrder] = useState(null);

  /* ─── Auto-generate order number + invoice number on mount ─── */
  useEffect(() => {
    if (prefilledOrderNumber) {
      setAutoGeneratedOrderNumber(prefilledOrderNumber);
      // Still generate invoice number
      api.get('/api/outlet-orders/generate-invoice-number').then(r => setAutoGeneratedInvoiceNumber(r.data.invoiceNumber)).catch(() => {});
      return;
    }
    const gen = async () => {
      try {
        const [orderRes, invoiceRes] = await Promise.all([
          api.get('/api/outlet-orders/generate-number'),
          api.get('/api/outlet-orders/generate-invoice-number')
        ]);
        setAutoGeneratedOrderNumber(orderRes.data.orderNumber);
        setAutoGeneratedInvoiceNumber(invoiceRes.data.invoiceNumber);
      } catch { setAutoGeneratedOrderNumber(''); setAutoGeneratedInvoiceNumber(''); }
    };
    gen();
  }, [prefilledOrderNumber]);

  /* ─── Customer Lookup (existing) ─── */
  const handleLookup = useCallback(async () => {
    const q = searchQuery.trim();
    if (!q) return toast.error('Enter phone number or name');
    setLookupLoading(true);
    setLookedUp(false);
    setClientData(null);
    setRecentOrders([]);
    setShowResults(false);
    try {
      const isPhone = /^[\d\-+ ]{7,}$/.test(q);
      const params = isPhone ? { phone: q } : { name: q };
      const res = await api.get('/api/outlet-orders/lookup', { params });
      const { clients } = res.data;
      if (clients.length === 1) {
        selectClient(clients[0].client, clients[0].recentOrders);
      } else {
        setSearchResults(clients);
        setShowResults(true);
        if (clients.length === 0) toast('Client not found — try a different search');
      }
      setLookedUp(true);
    } catch (err) {
      if (err.response?.status === 404) {
        setLookedUp(true);
        setClientData(null);
        toast('Client not found — try a different search');
      } else {
        toast.error('Lookup failed');
      }
    }
    setLookupLoading(false);
  }, [searchQuery]);

  const selectClient = useCallback((client, orders) => {
    setClientData(client);
    setShowResults(false);
    setSearchResults([]);
    setRecentOrders(orders || []);
    setCustomer({
      name: client.name || '',
      phone: client.phone || '',
      address: client.permanentAddress || '',
      city: client.city || (Array.isArray(client.deliveryAddresses) ? client.deliveryAddresses[0] : '') || '',
      notes: ''
    });

    const sizes = client.standardSizes || [];
    const chart = client.measurementChart || '';
    setClientStandardSizes(sizes);
    setClientMeasurementChart(chart);

    let loaded = false;
    let hasCustomFromDetails = false;
    let hasStandardFromDetails = false;
    let preSelectedSize = '';
    let normalized = {};
    setSizeData({});
    setClientMeasurements({});

    if (client.sizeDetails) {
      const raw = typeof client.sizeDetails === 'string'
        ? (() => { try { return JSON.parse(client.sizeDetails); } catch { return client.sizeDetails; } })()
        : client.sizeDetails;

      if (raw && typeof raw === 'object' && !Array.isArray(raw)) {
        const { _extra, ...rest } = raw;
        const isPerProduct = Object.values(raw).some(v => typeof v === 'object' && v !== null && !Array.isArray(v));
        if (isPerProduct) {
          const normalizedPerProduct = {};
          Object.entries(raw).forEach(([prodName, measurements]) => {
            if (typeof measurements === 'object' && measurements !== null && !Array.isArray(measurements)) {
              normalizedPerProduct[prodName] = {};
              Object.entries(measurements).forEach(([k, v]) => {
                if (k === '_extra' || k === '_standardSize') { normalizedPerProduct[prodName][k] = v; return; }
                const mapped = FIELD_NAME_MAP[k.toLowerCase()] || k;
                normalizedPerProduct[prodName][mapped] = v;
              });
            } else { normalizedPerProduct[prodName] = measurements; }
          });
          setSizeData(normalizedPerProduct);
          const first = Object.values(normalizedPerProduct).find(v => typeof v === 'object' && v !== null);
          if (first) { setClientMeasurements(first); hasCustomFromDetails = Object.keys(first).filter(k => k !== '_extra').length > 0; }
          loaded = true;
        } else if (Object.keys(rest).length > 0) {
          hasCustomFromDetails = true;
          Object.keys(rest).forEach(k => {
            const mapped = FIELD_NAME_MAP[k.toLowerCase()] || k;
            normalized[mapped] = rest[k];
          });
          if (_extra && Array.isArray(_extra)) normalized._extra = _extra;
          setClientMeasurements(normalized);
        }
      } else if (typeof raw === 'string' && raw.trim()) {
        hasStandardFromDetails = true;
        preSelectedSize = raw.trim().toUpperCase();
      }
    }

    if (!loaded && orders && orders.length > 0 && orders[0].sizeData) {
      try {
        const raw = typeof orders[0].sizeData === 'string' ? JSON.parse(orders[0].sizeData) : orders[0].sizeData;
        if (raw && typeof raw === 'object' && Object.keys(raw).length > 0) {
          setSizeData(raw);
          const first = Object.values(raw).find(v => typeof v === 'object' && v !== null);
          if (first) { setClientMeasurements(first); hasCustomFromDetails = true; }
          loaded = true;
        }
      } catch {}
    }

    const hasStandardOption = chart !== 'Custom Measurements' && (sizes.length > 0 || hasStandardFromDetails);
    const hasCustom = hasCustomFromDetails || chart === 'Custom Measurements';
    setSelectedStandardSize(preSelectedSize);
    if (hasStandardOption && hasCustom) setSizingMode('standard');
    else if (hasStandardOption) setSizingMode('standard');
    else if (hasCustom) setSizingMode('custom');
    else setSizingMode(null);

    toast.success(`Client ${client.name} loaded`);
  }, []);

  const handleStartNewCustomer = useCallback(() => {
    setCustomerMode('new');
    setClientData(null);
    setRecentOrders([]);
    setCustomer({ name: '', phone: '', address: '', city: '', notes: '' });
    setSizeData({});
    setClientMeasurements({});
    setClientStandardSizes([]);
    setSizingMode(null);
    setSelectedStandardSize('');
    setClientMeasurementChart('');
  }, []);

  const handleStartExistingCustomer = useCallback(() => {
    setCustomerMode('existing');
  }, []);

  /* ─── Product Management ─── */
  const addProduct = useCallback(() => {
    if (!newProduct.name.trim()) return toast.error('Enter product name');
    setProducts(prev => [...prev, { ...newProduct, _tempId: Date.now() + Math.random() }]);
    setNewProduct({ name: '', fabric: '', color: '', size: '', quantity: 1, unitPrice: 0, design: '', stitchingNotes: '', accessories: '', sleeveLength: '', shirtLength: '', measurementSpecialNote: '' });
  }, [newProduct]);

  const removeProduct = useCallback((idx) => setProducts(prev => prev.filter((_, i) => i !== idx)), []);

  const updateNewProduct = useCallback((field, value) => {
    setNewProduct(prev => ({ ...prev, [field]: value }));
  }, []);

  /* ─── Totals ─── */
  const totalAmount = useMemo(() => products.reduce((sum, p) => sum + (parseFloat(p.unitPrice) || 0) * (p.quantity || 1), 0), [products]);
  const advance = parseFloat(advanceAmount) || 0;
  const balance = totalAmount - advance;

  /* ─── Validation ─── */
  const canProceed = useMemo(() => {
    switch (step) {
      case 0:
        if (customerMode === 'existing') return lookedUp && clientData && customer.name.trim().length > 0;
        if (customerMode === 'new') return customer.name.trim().length > 0 && customer.phone.trim().length > 0;
        return false;
      case 1: return products.length > 0;
      case 2: return true;
      case 3: return true;
      case 4: return destination.length > 0;
      case 5: return true;
      default: return false;
    }
  }, [step, customerMode, lookedUp, clientData, customer, products, destination]);

  const nextStep = () => { if (canProceed) setStep(s => Math.min(s + 1, STEPS.length - 1)); };
  const prevStep = () => setStep(s => Math.max(s - 1, 0));

  /* ─── Submit ─── */
  const handleSubmit = async () => {
    if (products.length === 0) return toast.error('Add at least one product');
    if (!destination) return toast.error('Select an order destination');
    setSubmitting(true);
    try {
      const payload = {
        orderNumber: autoGeneratedOrderNumber || undefined,
        invoiceNumber: autoGeneratedInvoiceNumber || undefined,
        clientNumber: clientData?.clientNumber || null,
        isNewCustomer: customerMode === 'new' && !clientData,
        customerName: customer.name,
        customerPhone: customer.phone,
        address: customer.address,
        city: customer.city,
        notes: specialNotes || null,
        measurementSpecialNote: null,
        products: products.map(p => ({
          name: p.name,
          fabric: p.fabric,
          color: p.color,
          size: p.size,
          quantity: p.quantity,
          unitPrice: p.unitPrice,
          design: p.design,
          stitchingNotes: p.stitchingNotes,
          accessories: p.accessories,
          sleeveLength: p.sleeveLength || '',
          shirtLength: p.shirtLength || '',
          measurementSpecialNote: p.measurementSpecialNote || ''
        })),
        engravingRequired,
        engravingText: engravingText || null,
        engravingType: engravingType || null,
        engravingInstructions: engravingInstructions || null,
        logoRequired,
        logoDesign: logoDesign || null,
        engravingNames: engravingNames.length > 0 ? engravingNames : null,
        engravingLogos: engravingLogos.length > 0 ? engravingLogos : null,
        sizeData: Object.keys(sizeData).length > 0 ? sizeData : null,
        standardSize: sizingMode === 'standard' ? selectedStandardSize : null,
        measurementChart: sizingMode === 'custom' ? 'Custom Measurements' : (selectedStandardSize || null),
        advanceAmount: advance,
        orderDestination: destination,
        placedBy: localStorage.getItem('faisalEmployee') || null
      };
      const res = await api.post('/api/outlet-orders', payload);
      setCreatedOrder(res.data);
      setSubmitted(true);
      toast.success(`Order ${res.data.orderNumber} placed!`);
    } catch (err) {
      toast.error(err.response?.data?.message || 'Failed to place order');
    }
    setSubmitting(false);
  };

  const resetAll = () => {
    setStep(0);
    setCustomerMode(null);
    setSearchQuery('');
    setSearchResults([]);
    setShowResults(false);
    setClientData(null);
    setRecentOrders([]);
    setLookedUp(false);
    setCustomer({ name: '', phone: '', address: '', city: '', notes: '' });
    setProducts([]);
    setNewProduct({ name: '', fabric: '', color: '', size: '', quantity: 1, unitPrice: 0, design: '', stitchingNotes: '', accessories: '', sleeveLength: '', shirtLength: '' });
    setEngravingRequired(false);
    setEngravingText('');
    setEngravingInstructions('');
    setLogoDesign('');
    setSpecialNotes('');
    setMeasurementSpecialNote('');
    setSizeData({});
    setClientMeasurements({});
    setAdvanceAmount(0);
    setDestination('');
    setSubmitted(false);
    setCreatedOrder(null);
    setClientStandardSizes([]);
    setSizingMode(null);
    setSelectedStandardSize('');
    setClientMeasurementChart('');
    setAutoGeneratedOrderNumber('');
    setAutoGeneratedInvoiceNumber('');
    Promise.all([
      api.get('/api/outlet-orders/generate-number').then(r => setAutoGeneratedOrderNumber(r.data.orderNumber)).catch(() => {}),
      api.get('/api/outlet-orders/generate-invoice-number').then(r => setAutoGeneratedInvoiceNumber(r.data.invoiceNumber)).catch(() => {})
    ]);
  };

  /* ─── Render ─── */
  if (submitted) {
    return (
      <div className="min-h-screen flex items-center justify-center p-4">
        <div className="bg-gray-900 border-2 border-emerald-700 rounded-3xl p-8 max-w-md w-full text-center space-y-4">
          <div className="w-20 h-20 bg-emerald-500/20 rounded-full flex items-center justify-center mx-auto">
            <CheckCircle size={40} className="text-emerald-400" />
          </div>
          <h2 className="text-2xl font-black text-white">Order Placed!</h2>
          <p className="text-lg font-bold text-blue-400">{createdOrder?.orderNumber}</p>
          {createdOrder?.invoiceNumber && <p className="text-sm font-bold text-amber-400">Invoice: {createdOrder.invoiceNumber}</p>}
          <p className="text-sm font-bold text-gray-400">Routed to: {DESTINATIONS.find(d => d.value === destination)?.label || destination}</p>
          {customerMode === 'new' && (
            <p className="text-xs font-bold text-emerald-400">Customer saved to Client Registration</p>
          )}
          <div className="bg-gray-800 rounded-xl p-4 space-y-1 text-sm">
            <p className="text-gray-400">Total: <span className="text-white font-black">₨{totalAmount.toLocaleString()}</span></p>
            {advance > 0 && <p className="text-gray-400">Advance: <span className="text-emerald-400 font-black">₨{advance.toLocaleString()}</span></p>}
            <p className="text-gray-400">Balance: <span className="text-amber-400 font-black">₨{Math.max(0, balance).toLocaleString()}</span></p>
          </div>
          <button onClick={resetAll} className="w-full bg-blue-600 hover:bg-blue-500 text-white font-black py-3 rounded-xl text-sm">
            New Order
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto space-y-6 pb-20 px-4">
      {/* Header */}
      <div className="flex items-center gap-4">
        <div className="p-3 bg-amber-600 rounded-2xl"><ShoppingBag className="text-white" size={24} /></div>
        <div>
          <h1 className="text-2xl font-black text-white">Outlet Order Entry</h1>
          <p className="text-sm font-bold text-gray-400">{outletName}</p>
        </div>
      </div>

      {/* Step Indicator */}
      <div className="flex gap-1.5 overflow-x-auto pb-1">
        {STEPS.map((s, i) => (
          <button key={s} onClick={() => { if (i <= step) setStep(i); }}
            className={`text-[9px] font-black px-2 py-1.5 rounded-lg whitespace-nowrap uppercase tracking-wider transition-all shrink-0 cursor-pointer ${
              i === step ? 'bg-amber-600 text-white' :
              i < step ? 'bg-emerald-700/40 text-emerald-400' :
              'bg-gray-800 text-gray-500'
            }`}>
            {i + 1}. {s}
          </button>
        ))}
      </div>

      {/* Step Content */}
      <div className="bg-gray-900 border-2 border-gray-700 rounded-2xl p-4 md:p-6 space-y-4 min-h-[300px]">

        {/* ═══════════════════ Step 0: Customer ═══════════════════ */}
        {step === 0 && (
          <div className="space-y-4">
            <h2 className="text-lg font-black text-white flex items-center gap-2"><User size={18} />Customer</h2>

            {/* Mode Selection */}
            {!customerMode && (
              <div className="space-y-3">
                <p className="text-sm font-bold text-gray-400">How would you like to proceed?</p>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                  <button onClick={handleStartExistingCustomer}
                    className="bg-gray-800 hover:bg-gray-700 border-2 border-gray-700 hover:border-amber-500 rounded-2xl p-6 text-left transition-all">
                    <Search size={24} className="text-amber-400 mb-3" />
                    <p className="text-sm font-black text-white">Existing Customer</p>
                    <p className="text-xs font-bold text-gray-400 mt-1">Search by phone number to load saved data</p>
                  </button>
                  <button onClick={handleStartNewCustomer}
                    className="bg-gray-800 hover:bg-gray-700 border-2 border-gray-700 hover:border-emerald-500 rounded-2xl p-6 text-left transition-all">
                    <Plus size={24} className="text-emerald-400 mb-3" />
                    <p className="text-sm font-black text-white">New Customer</p>
                    <p className="text-xs font-bold text-gray-400 mt-1">Enter details directly — saved after order</p>
                  </button>
                </div>
              </div>
            )}

            {/* Existing Customer: Search */}
            {customerMode === 'existing' && !clientData && (
              <div className="space-y-3">
                <button onClick={() => setCustomerMode(null)} className="text-xs font-bold text-gray-500 hover:text-white flex items-center gap-1">
                  <ChevronLeft size={12} /> Back
                </button>
                <p className="text-sm font-bold text-gray-400">Search by phone number or name:</p>
                <div className="flex gap-2">
                  <input value={searchQuery} onChange={e => { setSearchQuery(e.target.value); setLookedUp(false); setShowResults(false); }}
                    placeholder="Phone number or name"
                    className="flex-1 bg-gray-800 border-2 border-gray-700 rounded-xl px-4 py-3 text-lg font-black text-white placeholder-gray-500 focus:border-amber-500 outline-none" />
                  <button onClick={handleLookup} disabled={lookupLoading || !searchQuery.trim()}
                    className="bg-amber-600 hover:bg-amber-500 text-white font-black px-6 py-3 rounded-xl disabled:opacity-50">
                    {lookupLoading ? '...' : 'Search'}
                  </button>
                </div>
                {showResults && searchResults.length > 1 && (
                  <div className="space-y-2">
                    <p className="text-xs font-bold text-gray-400">{searchResults.length} clients found — select one:</p>
                    <div className="max-h-64 overflow-y-auto space-y-2">
                      {searchResults.map(({ client, recentOrders: ro }, i) => (
                        <button key={i} onClick={() => selectClient(client, ro)}
                          className="w-full bg-gray-800 hover:bg-gray-700 border border-gray-700 rounded-xl p-3 text-left">
                          <p className="text-sm font-black text-white">{client.name} <span className="text-blue-400 text-xs">#{client.clientNumber}</span></p>
                          <p className="text-xs text-gray-400">{client.phone}{client.city ? ` — ${client.city}` : ''}</p>
                        </button>
                      ))}
                    </div>
                    <button onClick={handleStartNewCustomer} className="text-xs font-bold text-amber-400 hover:text-amber-300 underline">
                      Not found — enter as new customer
                    </button>
                  </div>
                )}
                {lookedUp && !clientData && !showResults && (
                  <div className="bg-amber-900/20 border border-amber-700 rounded-xl p-4">
                    <p className="text-sm font-bold text-amber-400">Client not found. </p>
                    <button onClick={handleStartNewCustomer} className="text-xs font-bold text-amber-300 underline mt-1">Enter as new customer instead</button>
                  </div>
                )}
              </div>
            )}

            {/* Existing Customer: loaded */}
            {customerMode === 'existing' && clientData && (
              <div className="space-y-3">
                <div className="bg-blue-900/20 border border-blue-700 rounded-xl p-3">
                  <p className="text-xs font-bold text-blue-400">Client #{clientData.clientNumber} — {clientData.name}</p>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="text-xs font-bold text-gray-400 block mb-1">Name *</label>
                    <input value={customer.name} onChange={e => setCustomer({ ...customer, name: e.target.value })}
                      className="w-full bg-gray-800 border-2 border-gray-700 rounded-xl px-4 py-3 text-sm font-bold text-white placeholder-gray-500 focus:border-amber-500 outline-none" />
                  </div>
                  <div>
                    <label className="text-xs font-bold text-gray-400 block mb-1">Phone *</label>
                    <input value={customer.phone} onChange={e => setCustomer({ ...customer, phone: e.target.value })}
                      className="w-full bg-gray-800 border-2 border-gray-700 rounded-xl px-4 py-3 text-sm font-bold text-white placeholder-gray-500 focus:border-amber-500 outline-none" />
                  </div>
                  <div>
                    <label className="text-xs font-bold text-gray-400 block mb-1">Address</label>
                    <input value={customer.address} onChange={e => setCustomer({ ...customer, address: e.target.value })}
                      className="w-full bg-gray-800 border-2 border-gray-700 rounded-xl px-4 py-3 text-sm font-bold text-white placeholder-gray-500 focus:border-amber-500 outline-none" />
                  </div>
                  <div>
                    <label className="text-xs font-bold text-gray-400 block mb-1">City</label>
                    <input value={customer.city} onChange={e => setCustomer({ ...customer, city: e.target.value })}
                      className="w-full bg-gray-800 border-2 border-gray-700 rounded-xl px-4 py-3 text-sm font-bold text-white placeholder-gray-500 focus:border-amber-500 outline-none" />
                  </div>
                </div>
                {recentOrders.length > 0 && (
                  <div className="border-t border-gray-700 pt-4">
                    <h3 className="text-xs font-black text-gray-400 uppercase tracking-wider mb-3">Recent Orders</h3>
                    <div className="space-y-2 max-h-48 overflow-y-auto">
                      {recentOrders.map(o => (
                        <div key={o.id} className="bg-gray-800/50 rounded-xl p-3 text-xs">
                          <p className="font-black text-blue-400">#{o.orderNumber}</p>
                          <p className="text-gray-500">{new Date(o.createdAt).toLocaleDateString()} — {o.currentStage}</p>
                          <p className="text-gray-500 mt-1">Total: ₨{(o.totalPrice || 0).toLocaleString()}</p>
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            )}

            {/* New Customer: Form */}
            {customerMode === 'new' && (
              <div className="space-y-3">
                <button onClick={() => setCustomerMode(null)} className="text-xs font-bold text-gray-500 hover:text-white flex items-center gap-1">
                  <ChevronLeft size={12} /> Back
                </button>
                <div className="bg-emerald-900/20 border border-emerald-700 rounded-xl p-3">
                  <p className="text-xs font-bold text-emerald-400">New customer — details will be saved to Client Registration after order is placed.</p>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="text-xs font-bold text-gray-400 block mb-1">Customer Name *</label>
                    <input value={customer.name} onChange={e => setCustomer({ ...customer, name: e.target.value })}
                      className="w-full bg-gray-800 border-2 border-gray-700 rounded-xl px-4 py-3 text-sm font-bold text-white placeholder-gray-500 focus:border-amber-500 outline-none"
                      placeholder="Full name" />
                  </div>
                  <div>
                    <label className="text-xs font-bold text-gray-400 block mb-1">Phone Number *</label>
                    <input value={customer.phone} onChange={e => setCustomer({ ...customer, phone: e.target.value })}
                      className="w-full bg-gray-800 border-2 border-gray-700 rounded-xl px-4 py-3 text-sm font-bold text-white placeholder-gray-500 focus:border-amber-500 outline-none"
                      placeholder="03XX-XXXXXXX" />
                  </div>
                  <div>
                    <label className="text-xs font-bold text-gray-400 block mb-1">Address</label>
                    <input value={customer.address} onChange={e => setCustomer({ ...customer, address: e.target.value })}
                      className="w-full bg-gray-800 border-2 border-gray-700 rounded-xl px-4 py-3 text-sm font-bold text-white placeholder-gray-500 focus:border-amber-500 outline-none"
                      placeholder="Street address" />
                  </div>
                  <div>
                    <label className="text-xs font-bold text-gray-400 block mb-1">City</label>
                    <input value={customer.city} onChange={e => setCustomer({ ...customer, city: e.target.value })}
                      className="w-full bg-gray-800 border-2 border-gray-700 rounded-xl px-4 py-3 text-sm font-bold text-white placeholder-gray-500 focus:border-amber-500 outline-none"
                      placeholder="City" />
                  </div>
                </div>
                <div>
                  <label className="text-xs font-bold text-gray-400 block mb-1">Customer Notes</label>
                  <textarea value={customer.notes} onChange={e => setCustomer({ ...customer, notes: e.target.value })}
                    className="w-full bg-gray-800 border-2 border-gray-700 rounded-xl px-4 py-3 text-sm font-bold text-white placeholder-gray-500 focus:border-amber-500 outline-none resize-none" rows={2}
                    placeholder="Any notes about the customer" />
                </div>
              </div>
            )}

            {/* Order Number + Invoice Number (always shown at bottom) */}
            {(autoGeneratedOrderNumber || autoGeneratedInvoiceNumber) && (
              <div className="bg-gray-800 rounded-xl p-3 flex flex-wrap items-center gap-3">
                {autoGeneratedOrderNumber && (
                  <>
                    <span className="text-xs font-bold text-gray-400">Order #</span>
                    <span className="text-sm font-black text-white tracking-wider">{autoGeneratedOrderNumber}</span>
                    <span className={`text-[10px] font-bold bg-gray-900 px-2 py-0.5 rounded-lg ${prefilledOrderNumber ? 'text-blue-400' : 'text-gray-500'}`}>{prefilledOrderNumber ? 'From POS' : 'Auto-generated'}</span>
                  </>
                )}
                {autoGeneratedInvoiceNumber && (
                  <>
                    <span className="text-xs font-bold text-gray-400 ml-2">Invoice #</span>
                    <span className="text-sm font-black text-amber-400 tracking-wider">{autoGeneratedInvoiceNumber}</span>
                    <span className="text-[10px] font-bold text-gray-500 bg-gray-900 px-2 py-0.5 rounded-lg">Auto-generated</span>
                  </>
                )}
              </div>
            )}
          </div>
        )}

        {/* ═══════════════════ Step 1: Products ═══════════════════ */}
        {step === 1 && (
          <div className="space-y-4">
            <h2 className="text-lg font-black text-white flex items-center gap-2"><ShoppingBag size={18} />Product Details</h2>
            <p className="text-xs font-bold text-gray-500">Enter each product manually. Add as many as needed.</p>

            {/* Add Product Form */}
            <div className="bg-gray-800 rounded-2xl p-4 space-y-3 border border-gray-700">
              <h3 className="text-xs font-black text-amber-400 uppercase tracking-wider">Add Product</h3>
              <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                <div className="col-span-2 md:col-span-4">
                  <label className="text-[10px] font-bold text-gray-500">Article / Product Name *</label>
                  <input value={newProduct.name} onChange={e => updateNewProduct('name', e.target.value)}
                    className="w-full bg-gray-900 border border-gray-700 rounded-lg px-3 py-2 text-sm font-bold text-white placeholder-gray-500 outline-none focus:border-amber-500"
                    placeholder="e.g. Men's Scrub Top, Lab Coat" />
                </div>
                <div>
                  <label className="text-[10px] font-bold text-gray-500">Fabric</label>
                  <input value={newProduct.fabric} onChange={e => updateNewProduct('fabric', e.target.value)}
                    className="w-full bg-gray-900 border border-gray-700 rounded-lg px-3 py-2 text-sm font-bold text-white placeholder-gray-500 outline-none focus:border-amber-500"
                    placeholder="e.g. Cotton, Polyester" />
                </div>
                <div>
                  <label className="text-[10px] font-bold text-gray-500">Color</label>
                  <input value={newProduct.color} onChange={e => updateNewProduct('color', e.target.value)}
                    className="w-full bg-gray-900 border border-gray-700 rounded-lg px-3 py-2 text-sm font-bold text-white placeholder-gray-500 outline-none focus:border-amber-500"
                    placeholder="e.g. Navy Blue" />
                </div>
                <div>
                  <label className="text-[10px] font-bold text-gray-500">Size</label>
                  <input value={newProduct.size} onChange={e => updateNewProduct('size', e.target.value)}
                    className="w-full bg-gray-900 border border-gray-700 rounded-lg px-3 py-2 text-sm font-bold text-white placeholder-gray-500 outline-none focus:border-amber-500"
                    placeholder="e.g. M, L, XL" />
                </div>
                <div>
                  <label className="text-[10px] font-bold text-gray-500">Qty</label>
                  <input type="number" value={newProduct.quantity} min="1"
                    onChange={e => updateNewProduct('quantity', Math.max(1, parseInt(e.target.value) || 1))}
                    className="w-full bg-gray-900 border border-gray-700 rounded-lg px-3 py-2 text-sm font-bold text-white outline-none focus:border-amber-500" />
                </div>
                <div>
                  <label className="text-[10px] font-bold text-gray-500">Unit Price (₨)</label>
                  <input type="number" value={newProduct.unitPrice} min="0"
                    onChange={e => updateNewProduct('unitPrice', Math.max(0, parseFloat(e.target.value) || 0))}
                    className="w-full bg-gray-900 border border-gray-700 rounded-lg px-3 py-2 text-sm font-bold text-white outline-none focus:border-amber-500" />
                </div>
                <div>
                  <label className="text-[10px] font-bold text-gray-500">Design / Style</label>
                  <input value={newProduct.design} onChange={e => updateNewProduct('design', e.target.value)}
                    className="w-full bg-gray-900 border border-gray-700 rounded-lg px-3 py-2 text-sm font-bold text-white placeholder-gray-500 outline-none focus:border-amber-500"
                    placeholder="e.g. V-Neck, Round Neck" />
                </div>
                <div className="col-span-2">
                  <label className="text-[10px] font-bold text-gray-500">Stitching Details</label>
                  <input value={newProduct.stitchingNotes} onChange={e => updateNewProduct('stitchingNotes', e.target.value)}
                    className="w-full bg-gray-900 border border-gray-700 rounded-lg px-3 py-2 text-sm font-bold text-white placeholder-gray-500 outline-none focus:border-amber-500"
                    placeholder="e.g. Double stitch, French seam" />
                </div>
                <div className="col-span-2">
                  <label className="text-[10px] font-bold text-gray-500">Required Accessories</label>
                  <input value={newProduct.accessories} onChange={e => updateNewProduct('accessories', e.target.value)}
                    className="w-full bg-gray-900 border border-gray-700 rounded-lg px-3 py-2 text-sm font-bold text-white placeholder-gray-500 outline-none focus:border-amber-500"
                    placeholder="e.g. Pocket, Zip, Buttons" />
                </div>
                <div>
                  <label className="text-[10px] font-bold text-gray-500">Sleeve Length</label>
                  <select value={newProduct.sleeveLength} onChange={e => updateNewProduct('sleeveLength', e.target.value)}
                    className="w-full bg-gray-900 border border-gray-700 rounded-lg px-3 py-2 text-sm font-bold text-white outline-none focus:border-amber-500">
                    <option value="">Select</option>
                    {SLEEVE_LENGTH_OPTIONS.map(o => (
                      <option key={o.value} value={o.value}>{o.label} — {o.labelUrdu}</option>
                    ))}
                  </select>
                </div>
                <div>
                  <label className="text-[10px] font-bold text-gray-500">Shirt Length</label>
                  <select value={newProduct.shirtLength} onChange={e => updateNewProduct('shirtLength', e.target.value)}
                    className="w-full bg-gray-900 border border-gray-700 rounded-lg px-3 py-2 text-sm font-bold text-white outline-none focus:border-amber-500">
                    <option value="">Select</option>
                    {SHIRT_LENGTH_OPTIONS.map(o => (
                      <option key={o.value} value={o.value}>{o.label} — {o.labelUrdu}</option>
                    ))}
                  </select>
                </div>
                <div className="col-span-2">
                  <label className="text-[10px] font-bold text-gray-500">Measurement Special Note</label>
                  <input value={newProduct.measurementSpecialNote} onChange={e => updateNewProduct('measurementSpecialNote', e.target.value)}
                    className="w-full bg-gray-900 border border-gray-700 rounded-lg px-3 py-2 text-sm font-bold text-white placeholder-gray-500 outline-none focus:border-amber-500"
                    placeholder="e.g. Chest 42, Waist 34, Loose fitting..." />
                </div>
              </div>
              <button onClick={addProduct}
                className="w-full bg-amber-600 hover:bg-amber-500 text-white font-black py-2.5 rounded-xl text-sm flex items-center justify-center gap-2 transition-all">
                <Plus size={16} /> Add Product
              </button>
            </div>

            {/* Products List */}
            {products.length > 0 && (
              <div className="space-y-2 border-t border-gray-700 pt-4">
                <h3 className="text-xs font-black text-gray-400 uppercase tracking-wider">Products ({products.length}) — Total: ₨{totalAmount.toLocaleString()}</h3>
                {products.map((p, idx) => (
                  <div key={p._tempId} className="bg-gray-800 rounded-xl p-3 space-y-2">
                    <div className="flex items-start justify-between gap-2">
                      <div className="flex-1">
                        <p className="text-sm font-black text-white">{p.name}</p>
                        <div className="flex flex-wrap gap-x-3 gap-y-0.5 mt-1 text-[11px] text-gray-400 font-bold">
                          {p.fabric && <span>Fabric: {p.fabric}</span>}
                          {p.color && <span>Color: {p.color}</span>}
                          {p.size && <span>Size: {p.size}</span>}
                          <span>Qty: {p.quantity}</span>
                          <span className="text-amber-400 font-black">₨{((p.unitPrice || 0) * (p.quantity || 1)).toLocaleString()}</span>
                        </div>
                        {p.design && <p className="text-[10px] text-gray-500 mt-0.5">Design: {p.design}</p>}
                        {p.sleeveLength && <p className="text-[10px] text-gray-500 mt-0.5">Sleeve: {p.sleeveLength}</p>}
                        {p.shirtLength && <p className="text-[10px] text-gray-500 mt-0.5">Shirt Length: {p.shirtLength}</p>}
                        {p.stitchingNotes && <p className="text-[10px] text-gray-500">Stitching: {p.stitchingNotes}</p>}
                        {p.accessories && <p className="text-[10px] text-gray-500">Accessories: {p.accessories}</p>}
                        {p.measurementSpecialNote && <p className="text-[10px] text-amber-400 font-bold mt-0.5">Measurement Note: {p.measurementSpecialNote}</p>}
                      </div>
                      <button onClick={() => removeProduct(idx)} className="text-red-400 hover:text-red-300 p-1"><X size={14} /></button>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        )}

        {/* ═══════════════════ Step 2: Engraving ═══════════════════ */}
        {step === 2 && (
          <div className="space-y-4">
            <h2 className="text-lg font-black text-white flex items-center gap-2"><FileText size={18} />Engraving / Customization</h2>
            <label className="flex items-center gap-2 text-sm font-bold text-white cursor-pointer">
              <input type="checkbox" checked={engravingRequired} onChange={e => setEngravingRequired(e.target.checked)}
                className="accent-amber-500 w-5 h-5" />
              Engraving Required
            </label>
            {engravingRequired && (
              <div className="space-y-4 pl-6">
                <div>
                  <label className="text-xs font-bold text-gray-400 block mb-1">Engraving Type</label>
                  <div className="flex gap-2">
                    {['direct', 'patch'].map(type => (
                      <button key={type} type="button" onClick={() => setEngravingType(type)}
                        className={`flex-1 py-3 rounded-xl text-xs font-black uppercase tracking-widest transition-all border-2 ${
                          engravingType === type
                            ? 'bg-amber-500/20 text-amber-400 border-amber-500'
                            : 'bg-gray-800 text-gray-400 border-gray-700 hover:border-gray-600'
                        }`}>
                        {type === 'direct' ? 'Direct Engraving' : 'Patch Engraving'}
                      </button>
                    ))}
                  </div>
                </div>
                <div>
                  <label className="text-xs font-bold text-gray-400 block mb-1">Engraving Text</label>
                  <input value={engravingText} onChange={e => setEngravingText(e.target.value)}
                    className="w-full bg-gray-800 border-2 border-gray-700 rounded-xl px-4 py-3 text-sm font-bold text-white placeholder-gray-500 focus:border-amber-500 outline-none"
                    placeholder="Text to engrave" />
                </div>
                <div>
                  <div className="flex items-center justify-between mb-1">
                    <label className="text-xs font-bold text-gray-400">Names for Engraving</label>
                    <button type="button" onClick={() => setEngravingNames(prev => [...prev, ''])}
                      className="text-[10px] font-black text-amber-400 hover:text-amber-300 flex items-center gap-1">
                      <Plus size={12} /> Add Name
                    </button>
                  </div>
                  <div className="space-y-2">
                    {engravingNames.map((name, i) => (
                      <div key={i} className="flex items-center gap-2">
                        <input value={name} onChange={e => { const next = [...engravingNames]; next[i] = e.target.value; setEngravingNames(next); }}
                          className="flex-1 bg-gray-800 border border-gray-700 rounded-lg px-3 py-2 text-xs font-bold text-white placeholder-gray-500 outline-none"
                          placeholder={`Name ${i + 1}`} />
                        <button onClick={() => setEngravingNames(prev => prev.filter((_, j) => j !== i))}
                          className="text-red-400 hover:text-red-300 p-1"><X size={14} /></button>
                      </div>
                    ))}
                  </div>
                </div>
                <div>
                  <label className="flex items-center gap-2 text-sm font-bold text-white cursor-pointer">
                    <input type="checkbox" checked={logoRequired} onChange={e => setLogoRequired(e.target.checked)}
                      className="accent-amber-500 w-5 h-5" />
                    Add Logo
                  </label>
                </div>
                {logoRequired && (
                  <div className="pl-6">
                    <div className="flex items-center justify-between mb-1">
                      <label className="text-xs font-bold text-gray-400">Logos</label>
                      <button type="button" onClick={() => setEngravingLogos(prev => [...prev, ''])}
                        className="text-[10px] font-black text-amber-400 hover:text-amber-300 flex items-center gap-1">
                        <Plus size={12} /> Add Logo
                      </button>
                    </div>
                    <div className="space-y-2">
                      {engravingLogos.map((logo, i) => (
                        <div key={i} className="flex items-center gap-2">
                          <input value={logo} onChange={e => { const next = [...engravingLogos]; next[i] = e.target.value; setEngravingLogos(next); }}
                            className="flex-1 bg-gray-800 border border-gray-700 rounded-lg px-3 py-2 text-xs font-bold text-white placeholder-gray-500 outline-none"
                            placeholder={`Logo ${i + 1} description`} />
                          <button onClick={() => setEngravingLogos(prev => prev.filter((_, j) => j !== i))}
                            className="text-red-400 hover:text-red-300 p-1"><X size={14} /></button>
                        </div>
                      ))}
                    </div>
                  </div>
                )}
                <div>
                  <label className="text-xs font-bold text-gray-400 block mb-1">Engraving Instructions</label>
                  <textarea value={engravingInstructions} onChange={e => setEngravingInstructions(e.target.value)}
                    className="w-full bg-gray-800 border-2 border-gray-700 rounded-xl px-4 py-3 text-sm font-bold text-white placeholder-gray-500 focus:border-amber-500 outline-none resize-none" rows={2}
                    placeholder="Font, position, style, etc." />
                </div>
                <div>
                  <label className="text-xs font-bold text-gray-400 block mb-1">Logo Design</label>
                  <input value={logoDesign} onChange={e => setLogoDesign(e.target.value)}
                    className="w-full bg-gray-800 border-2 border-gray-700 rounded-xl px-4 py-3 text-sm font-bold text-white placeholder-gray-500 focus:border-amber-500 outline-none"
                    placeholder="Logo name or design description" />
                </div>
                <div>
                  <label className="text-xs font-bold text-gray-400 block mb-1">Special Notes</label>
                  <textarea value={specialNotes} onChange={e => setSpecialNotes(e.target.value)}
                    className="w-full bg-gray-800 border-2 border-gray-700 rounded-xl px-4 py-3 text-sm font-bold text-white placeholder-gray-500 focus:border-amber-500 outline-none resize-none" rows={2}
                    placeholder="Production instructions, fabric notes, urgent delivery..." />
                </div>
              </div>
            )}
            {!engravingRequired && (
              <div className="space-y-4">
                <p className="text-sm text-gray-500">No engraving — tap Next to continue.</p>
                <div>
                  <label className="text-xs font-bold text-gray-400 block mb-1">Logo Design</label>
                  <input value={logoDesign} onChange={e => setLogoDesign(e.target.value)}
                    className="w-full bg-gray-800 border-2 border-gray-700 rounded-xl px-4 py-3 text-sm font-bold text-white placeholder-gray-500 focus:border-amber-500 outline-none"
                    placeholder="Logo name or design description" />
                </div>
                <div>
                  <label className="text-xs font-bold text-gray-400 block mb-1">Special Notes</label>
                  <textarea value={specialNotes} onChange={e => setSpecialNotes(e.target.value)}
                    className="w-full bg-gray-800 border-2 border-gray-700 rounded-xl px-4 py-3 text-sm font-bold text-white placeholder-gray-500 focus:border-amber-500 outline-none resize-none" rows={2}
                    placeholder="Production instructions, fabric notes, urgent delivery..." />
                </div>
              </div>
            )}
          </div>
        )}

        {/* ═══════════════════ Step 3: Measurements ═══════════════════ */}
        {step === 3 && (
          <div className="space-y-4">
            <h2 className="text-lg font-black text-white flex items-center gap-2"><Ruler size={18} />Measurement Special Notes</h2>

            <p className="text-xs font-bold text-gray-500">Enter measurement instructions for each product separately. Each product gets its own note.</p>

            {products.map((p, idx) => (
              <div key={p._tempId} className="bg-gray-800 rounded-xl p-4 space-y-2 border border-gray-700">
                <p className="text-sm font-black text-amber-400">{idx + 1}. {p.name} {p.color ? `(${p.color})` : ''}</p>
                <textarea
                  value={p.measurementSpecialNote}
                  onChange={e => {
                    const updated = [...products];
                    updated[idx] = { ...updated[idx], measurementSpecialNote: e.target.value };
                    setProducts(updated);
                  }}
                  className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-3 text-sm font-bold text-white placeholder-gray-500 focus:border-amber-500 outline-none resize-none"
                  rows={3}
                  placeholder={`Measurement instructions for ${p.name}...`}
                />
              </div>
            ))}
          </div>
        )}

        {/* ═══════════════════ Step 4: Destination ═══════════════════ */}
        {step === 4 && (
          <div className="space-y-4">
            <h2 className="text-lg font-black text-white flex items-center gap-2"><Send size={18} />Order Destination</h2>
            <p className="text-xs font-bold text-gray-500">Choose where this order should be sent.</p>
            <div className="space-y-2">
              {DESTINATIONS.map(d => (
                <button key={d.value} onClick={() => setDestination(d.value)}
                  className={`w-full text-left p-4 rounded-xl border-2 transition-all ${
                    destination === d.value ? 'border-amber-500 bg-amber-900/20' : 'border-gray-700 bg-gray-800 hover:bg-gray-750'
                  }`}>
                  <p className="text-sm font-black text-white">{d.label}</p>
                  <p className="text-xs font-bold text-gray-400">{d.desc}</p>
                </button>
              ))}
            </div>
          </div>
        )}

        {/* ═══════════════════ Step 5: Place Order ═══════════════════ */}
        {step === 5 && (
          <div className="space-y-4">
            <h2 className="text-lg font-black text-white flex items-center gap-2"><CheckCircle size={18} />Review & Place Order</h2>

            {/* Customer Info */}
            <div className="bg-gray-800 rounded-xl p-4 space-y-1 text-sm">
              <p className="text-gray-400">Customer: <span className="text-white font-black">{customer.name}</span></p>
              <p className="text-gray-400">Phone: <span className="text-white font-black">{customer.phone}</span></p>
              {customer.address && <p className="text-gray-400">Address: <span className="text-white font-bold">{customer.address}</span></p>}
              {customer.city && <p className="text-gray-400">City: <span className="text-white font-bold">{customer.city}</span></p>}
              {autoGeneratedOrderNumber && <p className="text-gray-400">Order #: <span className="text-white font-black">{autoGeneratedOrderNumber}</span></p>}
              {autoGeneratedInvoiceNumber && <p className="text-gray-400">Invoice #: <span className="text-amber-400 font-black">{autoGeneratedInvoiceNumber}</span></p>}
              {customerMode === 'new' && !clientData && (
                <p className="text-[10px] font-bold text-emerald-400 mt-1">New customer — will be saved to Client Registration</p>
              )}
            </div>

            {/* Products */}
            <div className="bg-gray-800 rounded-xl p-4 space-y-2 text-sm">
              <p className="text-gray-400 mb-2">Products: <span className="text-white font-black">{products.length} item(s)</span></p>
              {products.map((p, i) => (
                <div key={p._tempId} className="bg-gray-900 rounded-lg px-3 py-2 text-xs flex items-center justify-between">
                  <div>
                    <span className="text-white font-bold">{p.name}</span>
                    {p.fabric && <span className="text-gray-500 ml-1">({p.fabric})</span>}
                    {p.color && <span className="text-gray-500 ml-1">{p.color}</span>}
                    {p.size && <span className="text-gray-500 ml-1">/ {p.size}</span>}
                    {p.quantity > 1 && <span className="text-gray-500 ml-1">×{p.quantity}</span>}
                  </div>
                  <span className="text-amber-400 font-black">₨{((p.unitPrice || 0) * (p.quantity || 1)).toLocaleString()}</span>
                </div>
              ))}
            </div>

            {/* Engraving */}
            <div className="bg-gray-800 rounded-xl p-4 text-sm space-y-1">
              <p className="text-gray-400">Engraving: <span className="text-white font-black">{engravingRequired ? 'Yes' : 'No'}</span></p>
              {engravingRequired && engravingNames.length > 0 && (
                <p className="text-gray-400">Names: <span className="text-white font-black">{engravingNames.filter(Boolean).join(', ')}</span></p>
              )}
              {logoDesign && <p className="text-gray-400">Logo: <span className="text-white font-black">{logoDesign}</span></p>}
            </div>

            {/* Payment */}
            <div className="bg-gray-800 rounded-xl p-4 space-y-3">
              <div className="flex justify-between text-sm">
                <span className="text-gray-400 font-bold">Total Amount</span>
                <span className="text-white font-black">₨{totalAmount.toLocaleString()}</span>
              </div>
              <p className="text-[10px] font-bold text-gray-500">Payment handled at POS — no advance required here.</p>
            </div>

            {/* Destination */}
            <div className="bg-gray-800 rounded-xl p-4 text-sm">
              <p className="text-gray-400">Destination: <span className="text-white font-black">{DESTINATIONS.find(d => d.value === destination)?.label || destination}</span></p>
            </div>

            {/* Special Notes */}
            <div className="bg-gray-800 rounded-xl p-4 text-sm">
              {products.filter(p => p.measurementSpecialNote).length > 0 && (
                <div className="mb-1">
                  <p className="text-gray-400 font-bold mb-1">Measurement Notes:</p>
                  {products.filter(p => p.measurementSpecialNote).map((p, i) => (
                    <p key={p._tempId} className="text-amber-400 font-bold ml-2">• {p.name}: <span className="text-white">{p.measurementSpecialNote}</span></p>
                  ))}
                </div>
              )}
              {specialNotes && <p className="text-gray-400">Engraving Note: <span className="text-white font-black">{specialNotes}</span></p>}
              {logoDesign && <p className="text-gray-400">Logo: <span className="text-white font-black">{logoDesign}</span></p>}
            </div>

            <button onClick={handleSubmit} disabled={submitting}
              className="w-full bg-emerald-600 hover:bg-emerald-500 text-white font-black py-4 rounded-2xl text-lg disabled:opacity-50 flex items-center justify-center gap-2">
              {submitting ? 'Placing Order...' : `Place Order — ₨${totalAmount.toLocaleString()}`}
            </button>
          </div>
        )}

      </div>

      {/* Navigation */}
      <div className="flex gap-3">
        {step > 0 && (
          <button onClick={prevStep} className="flex-1 bg-gray-800 hover:bg-gray-700 text-white font-black py-3 rounded-xl text-sm flex items-center justify-center gap-2">
            <ChevronLeft size={16} />Back
          </button>
        )}
        {step < STEPS.length - 1 && (
          <button onClick={nextStep} disabled={!canProceed}
            className="flex-1 bg-amber-600 hover:bg-amber-500 text-white font-black py-3 rounded-xl text-sm disabled:opacity-50 flex items-center justify-center gap-2">
            Next <ChevronRight size={16} />
          </button>
        )}
      </div>
    </div>
  );
};

export default OutletOrderEntry;
